### ISSUE TITLE
Creo que seria bueno hacer que el log sea configurable

### ISSUE THREAD

**Issue by jackgris** [AndresXLP/ravenTree#2]
Creo que algo que podría ser interesante, para darle mayor versatilidad al querer usarlo en producción, es hacer que el log sea configurable ya sea agregarlo en la función `NewRavensTree` ( aunque va a ser un breaking change de la version 1), otra opción es agregar una función `SetLog` o algo así. Y la tercer opción que se me ocurre es agregarlo en el `struct Options`.

Para que puede ser útil esto, cuando uno quiere correr la aplicación en producción en general uno no quiere que el log solo vaya al `os.Stdout`. Sino que los puede querer salvar en un archivo, enviarlo a un DB, etc, etc.

**Comment by AndresXLP** [comment]
Claro que si lo tendré en cuenta para futuras actualizaciones.

**Comment by AndresXLP** [comment]
He decidido quitar los logs de la librería, esto para no tener la responsabilidad en conclusión el usuario es quien decide loguear por su cuenta, para la próxima release se vera el cambio.

**Comment by jackgris** [comment]
Me parece lo correcto.
