### ISSUE TITLE
Se podria remover el package echo y quizas poner los test que son de integracion en otro package

### ISSUE THREAD

**Issue by jackgris** [AndresXLP/ravenTree#3]
Esto no es absolutamente necesario, pero creo que podría ser bueno que no se dependa de otro paquete a menos que sea necesario como es el caso de echo, que puede ser reemplazado por la standard library ya que no se están haciendo cosas demasiado sofisticadas en el servidor de test.

Y lo otro, es que este tipo de test podría estar en su propio package, para que el test sea mas parecido a lo que un usuario puede usar o acceder de esta librería.

**Comment by AndresXLP** [comment]
Muchas gracias por todo, siempre es un gusto tener la ayuda que te hace ser mejor cada día. Un abrazo
